baseURL: "https://just-ary27.github.io/Lyf/" # for Deploying
languageCode: en-us
title: Lyf | Help Center
theme: PaperMod
defaultTheme: dark

disableKinds: ["section"]

params:
  profileMode:
    enabled: true
    title: " "
    # subtitle: "Lyf, Optimized"
    imageUrl: "images/lyf.svg" 
    imageTitle: "Lyf" # optional
    imageWidth: 520 # custom size
    imageHeight: 520 # custom size
  
menu:
  main: 
    - identifier:
      name: TODOs
      url: /todo/
      weight: 10
    - identifier:
      name: Diaries
      url: /diary/
      weight: 20
    - identifier:
      name: Settings
      url: /settings/
      weight: 30